name: Deploy to Cloudflare Pages

on:
  push:
    branches: [website]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install mise
        uses: jdx/mise-action@v2
      - name: Config mise
        run: mise settings experimental=true
      - name: Install dependencies
        run: mise install
      - name: Build
        run: mise run build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name ses-website --branch main
